baseURL = "https://hhhmgk.github.io/"
title = "Duc-Huy Ngo's site"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[pagination]
pagerSize = 20

# [services]
# [services.disqus]
# shortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Duc-Huy Ngo"
  info = "Software Engineer, Tech Enthusiast, (Mostly self claimed)"
  description = "Duc-Huy Ngo's personal place"
  keywords = "blog,developer,personal"
  # avatarurl = "images/avatar.jpg"
  gravatar = "ngoduchuy71123@gmail.com"

  # faviconSVG = "/img/favicon.svg"
  # favicon_32 = "/img/favicon-32x32.png"
  # favicon_16 = "/img/favicon-16x16.png"

  since = 2025

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/hhhmgk/"

# Menu links
[[menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"